CREATE TABLE t_cart
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id    BIGINT   NOT NULL COMMENT '用户',
    product_id BIGINT   NOT NULL COMMENT '商品',
    quantity   INT      NOT NULL DEFAULT 1 COMMENT '数量',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME COMMENT '软删除'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;