CREATE TABLE t_cart
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId    BIGINT   NOT NULL COMMENT '用户',
    productId BIGINT   NOT NULL COMMENT '商品',
    quantity   INT      NOT NULL DEFAULT 1 COMMENT '数量',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME COMMENT '软删除'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;